"""initial migration

Revision ID: ffd94d97b91e
Revises: 
Create Date: 2020-08-31 19:27:23.414247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffd94d97b91e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('password_hash'),
    sa.UniqueConstraint('username')
    )
    op.create_table('delivery_charge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address_pin', sa.String(length=6), nullable=False),
    sa.Column('amount', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address_pin')
    )
    op.create_table('product_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_name')
    )
    op.create_table('shop_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_name', sa.String(length=128), nullable=False),
    sa.Column('shop_email', sa.String(length=64), nullable=False),
    sa.Column('contact_phone', sa.String(length=10), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_phone'),
    sa.UniqueConstraint('shop_email'),
    sa.UniqueConstraint('shop_name')
    )
    op.create_table('status_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status_name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_name', sa.String(length=64), nullable=False),
    sa.Column('unit_short', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_name'),
    sa.UniqueConstraint('unit_short')
    )
    op.create_table('order_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status_time', sa.DateTime(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('status_catalog_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['status_catalog_id'], ['status_catalog.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status_time')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=128), nullable=False),
    sa.Column('product_weight', sa.Integer(), nullable=False),
    sa.Column('product_description', sa.String(length=255), nullable=False),
    sa.Column('price_per_unit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('product_image', sa.String(length=256), nullable=False),
    sa.Column('product_type_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_type_id'], ['product_type.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_name')
    )
    op.create_table('placed_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_placed', sa.DateTime(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('delivery_address', sa.Text(), nullable=False),
    sa.Column('delivery_address_pin', sa.String(length=6), nullable=True),
    sa.Column('delivery_charge', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('customer_name', sa.String(length=128), nullable=False),
    sa.Column('customer_contact_phone', sa.String(length=10), nullable=False),
    sa.Column('customer_address', sa.Text(), nullable=False),
    sa.Column('customer_address_pin', sa.String(length=6), nullable=False),
    sa.Column('order_status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_status_id'], ['order_status.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('time_placed')
    )
    op.create_table('stock',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('in_stock', sa.Integer(), nullable=False),
    sa.Column('last_update_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('last_update_time')
    )
    op.create_table('order_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('placed_order_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['placed_order_id'], ['placed_order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_item')
    op.drop_table('stock')
    op.drop_table('placed_order')
    op.drop_table('products')
    op.drop_table('order_status')
    op.drop_table('units')
    op.drop_table('status_catalog')
    op.drop_table('shop_details')
    op.drop_table('product_type')
    op.drop_table('delivery_charge')
    op.drop_table('admin')
    # ### end Alembic commands ###
